// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE470eqjU0mb2QLi6EjA1tSTCfWbr5gVE',
    appId: '1:499388130973:web:071bd80d0fc65bf9c1d674',
    messagingSenderId: '499388130973',
    projectId: 'roommate-matching-platform',
    authDomain: 'roommate-matching-platform.firebaseapp.com',
    storageBucket: 'roommate-matching-platform.firebasestorage.app',
    measurementId: 'G-6LL3QKQVSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSlSI5JMygn585-10Fy2nqiFkvV4gIAcQ',
    appId: '1:499388130973:android:388b519ad08b709dc1d674',
    messagingSenderId: '499388130973',
    projectId: 'roommate-matching-platform',
    storageBucket: 'roommate-matching-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWoqDJL5jKyd8j2beUvtcriXYPbG2nchI',
    appId: '1:499388130973:ios:8148f7bdfe9eb13ec1d674',
    messagingSenderId: '499388130973',
    projectId: 'roommate-matching-platform',
    storageBucket: 'roommate-matching-platform.firebasestorage.app',
    iosBundleId: 'com.example.roommateMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWoqDJL5jKyd8j2beUvtcriXYPbG2nchI',
    appId: '1:499388130973:ios:8148f7bdfe9eb13ec1d674',
    messagingSenderId: '499388130973',
    projectId: 'roommate-matching-platform',
    storageBucket: 'roommate-matching-platform.firebasestorage.app',
    iosBundleId: 'com.example.roommateMatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE470eqjU0mb2QLi6EjA1tSTCfWbr5gVE',
    appId: '1:499388130973:web:7a41ec144f35de49c1d674',
    messagingSenderId: '499388130973',
    projectId: 'roommate-matching-platform',
    authDomain: 'roommate-matching-platform.firebaseapp.com',
    storageBucket: 'roommate-matching-platform.firebasestorage.app',
    measurementId: 'G-TVKG3WNJHY',
  );
}
